BLOCK_MAPPINGS = {
    "AIR": 0,
    "DEEPSLATE": 1,
    "BEDROCK": 2,
    "DEEPSLATE_IRON_ORE": 3,
    "DEEPSLATE_DIAMOND_ORE": 3,
    "DEEPSLATE_GOLD_ORE": 3,
    "DEEPSLATE_LAPIS_ORE": 3,
    "DEEPSLATE_REDSTONE_ORE": 3,
}